### ISSUE TITLE
Aula Oled Support 

### ISSUE THREAD

**Issue by TriceTheLegend** [Hartie95/fastCFWswitch#16]
If would be great if you would make it possible that fastCFWSwitch works with a OLED switch. 
Thank you for your work

**Comment by tma533026** [comment]
I also hope to support OLED, thanks to the author for his efforts.

**Comment by TTghostsemir** [comment]
I have a Version for Mariko!

**Comment by TTghostsemir** [comment]
https://github.com/TTghostsemir/fastCFWswitch/releases/tag/1.3.1_mod

**Comment by Hartie95** [comment]
> https://github.com/TTghostsemir/fastCFWswitch/releases

I checked the changes, you just removed the mariko check, but didn't add any real support. So all configurations are pretty much ignored. 
Just use the reboot to payload app from atmosphere, use a general reboot app or OS reboot, or make a simper overlay that just does the reboot to payload without any configurations for that. 

Generally it seems not possible to support mariko for now, since even with the newer hekate changes, the registers used by it are overwritten by the os on reboot, according to the Studious-Pancake dev.
