### ISSUE TITLE
Trouble setting up config

### ISSUE THREAD

**Issue by RebelLion420** [Hartie95/fastCFWswitch#7]
I am attempting to set up the config for rebooting between my emuMMC and sysMMC, but I can't get it to reboot into anything but straight into Sept Atmosphere everytime (what the bootlogo shows), which is my emuMMC for some reason. I think my issue is not knowing which payload to pick or how to set it up. I followed the homebrew setup page using the SD card setup website and ended up with a fusee-primary.bin in my /bootloader/payloads. But when I checked hekate's config, it was booting with fss0=/atmosphere/fusee-secondary.bin so I thought that must be the payload. Plugging that in instead causes the overlay to not even function, clicking either CFW changes the text I clicked to "rebooting" and at the top where the version number was it says "to big". Spelled exactly like that. Not sure what I need to provide but I can upload copies of my configs if needed

**Comment by phisch** [comment]
I recently wanted to do the same, and i had the same assumption as you that `/atmosphere/fusee-secondary.bin` would be the payload to boot into stock sysnand.

It turns out that assumtion isn't right.

You can boot into stock sysnand by booting into hekate and passing in a `bootId` that matches the boot entry in your hekate configuration.

For example in your `/bootloader/hekate_ipl.ini`:
```ini
[Stock SysNAND]
id=stock
fss0=atmosphere/fusee-secondary.bin
stock=1
emummc_force_disable=1
icon=bootloader/res/switch.bmp
```

Notice the `id=stock` which you can set to anything you like. You'll reference it in your `/config/fastCFWSwitch/config.ini` like this:

```ini
[FIRMWARES]
name=Firmwares (through hekate)

[SYSNAND]
name=sysnand (stock)
path=/hekate_ctcaer_5.5.7.bin
bootId=stock
```
Notice that this uses the hekate payload, and passes in `bootId=stock` which matches the `id=stock` from hekates config above.

I hope this solves your issue!
